name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Pull Docker image from Docker Hub
        run: docker pull docker.io/library/spring-petclinic:3.3.0-SNAPSHOT

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Tag the Docker image
        run: docker tag docker.io/library/spring-petclinic:3.3.0-SNAPSHOT ghcr.io/${{ github.repository_owner }}/spring-petclinic:3.3.0-SNAPSHOT

      - name: Push the Docker image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.repository_owner }}/spring-petclinic:3.3.0-SNAPSHOT
